### ISSUE TITLE
lecture-cy Anpassungen

### ISSUE THREAD

**Issue by cyildiz** [cagix/Hugo-Lecture-Archetypes#4]
- outcomes.md  --> outcomes_draft.md  (damit die zugehörige Section nicht by default angezeigt wird).
- In index.md zentrierten "under construction" Text hinzufügen, manche keys auskommentieren.

**Comment by cyildiz** [comment]
@cagix , ich wollte diese Issue an mich assignen, kann ich im Moment nicht. woran könnte das liegen?

**Comment by cagix** [comment]
> @cagix , ich wollte diese Issue an mich assignen, kann ich im Moment nicht. woran könnte das liegen?

in den settings steht, dass dein invite noch pending ist. du müsstest dazu eine mail mit einer einladung von github bekommen haben (letzte/vorletzte woche). ich versuche mal, die einladung zurückzuziehen und dann erneut auszuführen, damit du nochmal ne aktuelle mail kriegst.

**Comment by cagix** [comment]
> * outcomes.md  --> outcomes_draft.md  (damit die zugehörige Section nicht by default angezeigt wird).

was ist denn das ziel dieser umbenennung? geht es darum, dass in einer unbearbeiteten seite dann leere lernziele stehen? dann würde ich eher analog zum `index.md`  einen hinweis o.ä. einbauen, der dann so lange erscheint, bis du die lernziele bearbeitet hast oder entschieden hast, dass es keine explizit benannten lernziele für diese sitzung gibt?

das umbenennen ergibt im git ein ziemliches hin- und her.



> * In index.md zentrierten "under construction" Text hinzufügen, manche keys auskommentieren.

finde ich gut :)  

---


alternativ könnte ich mir einen schalter in deinem `index.md` vorstellen, der genau dies **alles** erledigt: keine Einbindung von irgendwas, stattdessen nur ein hinweis als "content". und wenn du dann fertig bist, musst du nur die zeile mit dem schalter entfernen. das fände ich sauberer. das könnte sowas wie `draft: true` sein, nur dass `draft` schon von hugo belegt ist und zu anderen ergebnissen führt.

**Comment by cyildiz** [comment]
Super Idee! Danke für den Tip.
Das Dateinamen-Umbenennen war mir auch nicht ganz geheuer :)
Ich werde in der `index.md` ein `outcomes:false` hinzufügen.
Im `single.html` füge ich dann die entsprechende Abfrage ein.

**Comment by cagix** [comment]
> Ich werde in der `index.md` ein `outcomes:false` hinzufügen.
> Im `single.html` füge ich dann die entsprechende Abfrage ein.

die abfrage kann ich gern nachher noch einbauen, ich muss ja sowieso noch an einige dinge dran.

die frage ist, soll es einfach nur `outcomes:false` sein? das würde sich dann nur auf die lernziele beschränken?

wenn ich dich richtig verstanden hatte, willst du ja gleichzeitig alle automatischen inhalte beim rendering abschalten (und nicht nur die outcomes) und stattdessen eine zentrale "message" setzen, nach der die seite noch im aufbau ist (oder so ähnlich). dann wäre der schaltername für mich eher sowas wie `sketch` oder `preliminary`? (`draft` wäre eigentlich genau richtig, ist aber bereits durch hugo belegt.)

**Comment by cagix** [comment]
> > Im `single.html` füge ich dann die entsprechende Abfrage ein.
> 
> die abfrage kann ich gern nachher noch einbauen, ich muss ja sowieso noch an einige dinge dran.

das gehört nach https://github.com/cagix/Hugo-Lecture-Layouts ... habe dafür ein neues issue erstellt: https://github.com/cagix/Hugo-Lecture-Layouts/issues/24

aber wir sollten hier jetzt zuende besprechen, wie das dokument aussehen soll, wenn du den schalter aktivierst :)

**Comment by cyildiz** [comment]
Für die anderen keys (readings, quizzes, assignments, videos) gibt es bereits die Abfrage in den zugehörigen shortcuts.

Die Quizzes-Section erscheint z.B. nur, wenn der quizzes-key in `index.md` definiert ist.
Ich kann diesen Key einfach löschen oder auskommentieren, und so das Rendering der gesammten Quizzes-Box aus dem `index.md` aus kontrollieren/verhindern. 

Den Schalter brauche ich nur für die Lernizele/Outcomes. Dort wird das Vorhandensein einer Datei abgefragt. Falls es die Datei gibt (und es gibt sie immer), wird die Lernziele-Box gerendert (farbige Box mit der Überschrift "Lernziele", ohne weiteren Inhalt). Das wollte ich abschalten können.

**Comment by cagix** [comment]
ok, dann machen wir das so.

ich hatte den eindruck, dass es mit einer art zentralem schalter einfacher wird, da du dann alle anderen sachen so lassen kannst bzw. sogar schrittweise aufbauen kannst und trotzdem nur ein "im aufbau" über dein template angezeigt wird, bis du den schalter deaktivierst und damit dann die eigentlichen inhalte sichtbar machst. du müsstest dann beispielsweise die variable für die assignments oder die videos nicht erst löschen/auskommentieren, um sie dann später doch wieder reinzunehmen?

**Comment by cagix** [comment]
der workflow mit dem zentralen schalter wäre: 

- du erstellst die ordner und dateien über die archetypen, wobei alles (variablen, hilfsdateien, ...) angelegt ist
- der zentrale schalter im index.md ist aktiv
- du schiebst diese lektion per pull-request in den master
- in der webseite wird durch den schalter über das template ein "im aufbau, kommt bald" angezeigt
- du arbeitest die inhalte in einem feature-branch aus; wenn du fertig bist, löscht du die zeile mit dem schalter und schiebst die seite bis pull-request in den master
- die seite wird mit allen inhalten wie konfiguriert angezeigt, d.h. wenn es dann eine variable oder hilfsdatei nicht gibt, wird dazu nichts gerendert

das scheint mir einfacher zu sein, als mehrere dinge temporär zu löschen/auszukommentieren und dann später doch wieder einzufügen? dann müsste die "im aufbau"-zeile beispielsweise auch nicht in den archetypen und müsste dann nicht nochmal wieder entfernt werden ...

**Comment by cyildiz** [comment]
Das ist eine gut Idee, um den "im Aufbau" Prozess zu lösen.

Das löst aber alleine nicht den folgenden Fall, oder verstehe ich hier etwas falsch: 
Alle Inhalte für eine lecture/topic sind fertig ausgearbeitet. Der zentrale Schalter wird geöffnet. Es sind zu diesem topic aber keine Lernziele angegeben (outcomes.md ist leer). ---> Leere Lernziele-Section wird gerendert.

Oder sollte ich die outcomes.md Datei löschen, falls es keine Lernziele geben soll?
Später, wenn irgendwann Lernziele dazukommen, die Datei neu erstellen?

Die Lernziele doch nicht in eine separate Datei auszulagern wäre auch eine Möglichkeit.
Die jetzige Reihenfolge der Inhalte hatte eine separate Datei notwendig gemacht.
Ich könnte die Reihenfolge so ändern, dass ich die Lernziele wie ursprünglich mit in die `index.md` nehme.

**Comment by cagix** [comment]
> Das löst aber alleine nicht den folgenden Fall, oder verstehe ich hier etwas falsch:
> Alle Inhalte für eine lecture/topic sind fertig ausgearbeitet. Der zentrale Schalter wird geöffnet. Es sind zu diesem topic aber keine Lernziele angegeben (outcomes.md ist leer). ---> Leere Lernziele-Section wird gerendert.
> 
> Oder sollte ich die outcomes.md Datei löschen, falls es keine Lernziele geben soll?
> Später, wenn irgendwann Lernziele dazukommen, die Datei neu erstellen?

genau so hatte ich das im kopf. bei einer fertigen seite sind nur die artefakte und variablen aktiv, die auch konkret gebraucht werden. wenn also die "fertige" seite keine lernziele hat, sollte die datei `outcomes.md` auch einfach gelöscht werden. und wenn du dann irgendwann (nächstes jahr?) doch noch lernziele definieren willst oder erst dann dazu kommst, dann kann man die datei ja manuell aus dem `archetypes/` rüberkopieren und befüllen.


> Die Lernziele doch nicht in eine separate Datei auszulagern wäre auch eine Möglichkeit.
> Die jetzige Reihenfolge der Inhalte hatte eine separate Datei notwendig gemacht.

ja, ich finde das mit dem auslagern auch etwas overkill. aber das fängt eigentlich bereits mit der ordner-sache an. eigentlich sollten dateien für eine seite reichen. nur unterliegen dann die resourcen (bilder, ...) bereits so blöden beschränkungen, und dann durch die template-sache muss ich mir die sachen halt irgendwie aus einzelnen dateien zusammen bauen.

man könnte jetzt natürlich das template nochmal so ändern, dass die outcomes mit in den index.md kommen könnten. aber du hattest ja gute gründe für deinen template-aufbau :)

alternativ könnte man natürlich die outcomes und das tldr/recap über eine variable im yaml erzeugen. das hatte ich letztes jahr gemacht. bei den outcomes geht das noch halbwegs, das sind ja in der regel wenige stichpunkte. aber das recap/tldr ist ja in der regel ein oder zwei absätze mit formatierung etc, und da kriegt der yaml-header ganz schön schlagseite. zumal man immer alles zusätzlich zwei spaces einrücken muss ...

**Comment by cagix** [comment]
@cyildiz Ich habe in die Archetypen ein `sketch: true`  und zusätzlich in Deinen Archetypen ein `outcomes: false` eingebaut. Damit sind die Archetypen wieder synchron zu den Layouts (siehe https://github.com/cagix/Hugo-Lecture-Layouts/issues/24)
